export const HOST = "http://localhost:3000";
export const FETCH_CONTENT_API = `${HOST}/api/v1/fetchContent`;
export const SAVE_CONTENT_API = `${HOST}/api/v1/saveContent`;
export const SCAN_CONTENT_API = `${HOST}/api/v1/scanContent`;
export const CREATE_CONTENT_API = `${HOST}/api/v1/createContent`;
export const GROQ_API = "/api/v1/groq";
export const CONTENT_DIR = "content";
export const PLATFORMS = ["twitter", "reddit", "linkedin", "blog", "github"];
export const FIELDS = ["content", "title", "keywords", ...PLATFORMS];
